### PR TITLE
Fixes issues with endian macros (in GCC)

### LINKED ISSUE #481: wieredness with BIG_ENDIAN macro
Starting with GCC 5.4.1 the BIG_ENDIAN define seems to be defined internally in the compiler.
This has been reported by @cw2 in #474. I can confirm that I'm seeing this too on my builds.

I've opened a ticket with GNU ARM Embedded Toolchain. Waiting on their comments.
Thinking on a solution for this, I found that CMSIS has a macro defined for this purpose (see "Pre-processor Macros" in [http://www.keil.com/pack/doc/cmsis/DSP/html/index.html](url). It's ARM_MATH_BIG_ENDIAN. As we seem to be moving towards CMSIS and we are already using other macros from there (__FPU_PRESENT for example), suggest that the current BIG_ENDIAN in NETMF is replaced with ARM_MATH_BIG_ENDIAN.

I can submit a PR for this immediately.

### PR DESCRIPTION
**Pull request by josesimoes**
Fixes #481

### CODE REVIEW

**Comment by smaillet-ms** [comment]
Pease squash those merges out so it makes for a clean merge to main. Other than that I'm 👍 on this.

**Comment by josesimoes** [comment]
I have those two first two commits hanging on my fork for quite some time.
I don't know who to remove those. Tried several approaches without any luck.
Apologies but my GitHub knowledge is very limited...

**Comment by smaillet-ms** [comment]
use: `git rebase -i` this will pop up your text editor with a list of the changes and some instructions. You can use the word 'squash' to squash those merges so they are effectively ignored as an independent commit that can be rolled back. This helps keep the history on the main branch cleaner as a pull request should be focused on doing one thing so it can be rolled back as a complete unit if needed.

**Comment by josesimoes** [comment]
Before I totally loose my sanity with the GitHub command line, I'm closing this PR and will submit a new one. Hopefully meeting the requirements...

**Pull request closed without merging**
