### PR TITLE
Added barebone STM32F4DISCOVERY solution

### PR DESCRIPTION
**Pull request by cw2**
This is a minimal STM32F4DISCOVERY solution, for #26. It is based on MCBSTM32F400_NONET, so no RTOS.

The MDK build seems to be working fine, I have verified TinyBooter commands in MFDeploy, flashing TinyCLR, application deployment and debugging from Visual Studio.

The GCC build (using the latest GCC ARM Embedded Tools 4.9.3) has working TinyBooter, but there is a problem with TinyCLR, which can be flashed fine and runs, but there seems to be some memory corruption or invalid settings, because the MFDeploy "Memory Map" command returns wrong result for RAM  (the reported address is in flash range). I suspect I overlooked something...

Notes:
* The bootloader mode is indicated by turning on all four user LEDs
* The User button does not work yet, so it is not possible to switch to bootloader on startup (sorry).
* GCC uses newlib-nano, generated code is about the same size as produced by MDK, i.e. the flash memory layout stays the same (scatterfile, BlockRange).
* Code from pull request #153 is already included.

### CODE REVIEW

**Comment by Stabilitronas** [comment]
Wow, this is so cool! Good job!

**Comment by smaillet-ms** [comment]
I'd recommend comparing and updating this code base to the latest MCBSTM32F400 support in this branch, a number of issues were resolved there that don't appear in this new cloned solution.

**Comment by cw2** [comment]
Could you please be more specific on what is not included? The branch is based on commit 7efe0092892f1b4ac977cdfd2dc6901b898d9040 from 6/6/2015 6:31:47 PM and there are no additional changes in MCBSTM32F400 solution after that (?) Or is the pull request wrong?

**Comment by smaillet-ms** [comment]
you based this on MCBSTM32F400_NONET, which no longer exists. A number of changes were made to the GCC support and the Keil board solution. (And there's still more to go) so it's probably worth double checking to see if any of the changes matter.

**Comment by cw2** [comment]
I have fixed the RAM layout and STM32F4DISCOVERY solution build by GCC seems to be working: flashing TinyCLR from bootloader, MFDeploy commands, application deployment and debugging from Visual Studio.

**Comment by smaillet-ms** [comment]
:+1:

**Pull request merged**
