### PR TITLE
Add NETMF logo

### PR DESCRIPTION
**Pull request by aline-almeida**

### CODE REVIEW

**Comment by smaillet-ms** [comment]
Can you find a color match for the grey that matches the logo? The Color on this isn't quite a correct match.

**Comment by aline-almeida** [comment]
Maybe you could supply the correct hex color code.

**Comment by cw2** [comment]
#404040 Gray25

**Comment by aline-almeida** [comment]
@smaillet-ms:  is #404040 the right color?

**Comment by cw2** [comment]
@aline-almeida I don't mean to be impolite, but what's the problem with opening the original PNG image in your favorite graphics editor (even Paint or Visual Studio) and use the Color Picker tool to get the color?

**Comment by aline-almeida** [comment]
@cw2 None at all, just checking if that was ok.

**Pull request merged**
