### PR TITLE
Merging in support For GCC

### PR DESCRIPTION
**Pull request by smaillet-ms**
merges in all changes from the GCC support work from the active community into the core dev branch where all additional support for GCC will continue. (The previous Support-GCC branch will be removed)

### CODE REVIEW

**Comment by piwi1263** [comment]
Wow, :+1:

**Comment by smaillet-ms** [comment]
Wow, indeed, it's a huge number of changes and it merged pretty easily (After the last big merge on this  made such a mess I was really worried) Major :clap: and :beers: to all contributors on this one - true community team effort the way we really want to see this project go forward!

**Comment by piwi1263** [comment]
So, is this now official, support for gcc compile for netmf ... so I can shout it out to ...

**Comment by Injac** [comment]
Compiled the STM32F4DISCOVERY solution a few minutes ago - no errors so far! Great work! Thanks                                  !
2015-06-25 04_58_09-new notification

**Comment by josesimoes** [comment]
Awesome! :+1:

**Pull request merged**
