### PR TITLE
enc28j60 problem fixed

### PR DESCRIPTION
**Pull request by techcap**
In enc28j60, GLOBAL_LOCK and pbuf_alloc interferes and finally go to fault.
Fixed the problem.

### CODE REVIEW

**Comment by josesimoes** [comment]
:+1:

**Comment by smaillet-ms** [comment]
FYI: we haven't forgotten this, we are holding pull requests that aren't bug fixes critical to the v4.4 release until we get that release out. Once it is out (shortly) we'll come back to all pending pull requests

**Comment by techcap** [comment]
Thanks^^ Now I'm on long running test.

**Comment by josesimoes** [comment]
@techcap could you please let me know with what solution you've got the ENC28J60 working? Can you share the TinYCLR project file? Did you build the solution using GCC or MDK?
Thanks!

**Pull request merged**
