### PR TITLE
Update for BitConverter that avoids reinterpret cast on unaligned memory

### LINKED ISSUE #306: Running BitConverter tests crashes
Running BitConverter tests on MCBSTM32F400 (Keil) crashes and make the board not responsive. I have to erase the deployment region to make it work again.

### PR DESCRIPTION
**Pull request by doingnz**
reinterpret_cast<T>(v) is in general dangerous. It can inadvertently attempt to access unaligned memory when it tries to cast a BYTE\* to something else. To avoid this risk, this update creates a local variable of the required type, then copies the byte aligned values byte by byte into this local variable before using the local variable to set the return value on the stack. Used the same code layout for all for readability. Assuming compiler will optimize sufficiently. 

The existing Unit Tests will all pass when run on iMXS system after applying this update.   

Hopefully fixes #306 

Note the pull also includes changes for adding ARM compiler DS5. I am not sure how to create a pull request that only includes the BitConverter change.

### CODE REVIEW

**Comment by smaillet-ms** [comment]
Please squash those commits down to a single commit (There's a lot of merging going on that's not historically relevant to the actual changes made)

**Comment by smaillet-ms** [comment]
Also, please split out the DS5 support. Pull requests should focus on single fix/feature so they are easier to understand and if needed, roll back.

**Comment by smaillet-ms** [comment]
@doingnz any chance of updating this PR as requested in comments? Otherwise it will be closed without merging into the main tree.

**Comment by uscomrs** [comment]
I have created a new Pull Request #395 with the changes based on the latest 'dev' branch.

**Comment by smaillet-ms** [comment]
Thanks for the update!

**Pull request closed without merging**
